### ISSUE TITLE
Duplicated Content

### ISSUE THREAD

**Issue by Kacaii** [Kacaii/Senac-Coding#3]
# Table of Contents

There are **two** Tables of Content in the README file.

## TODO

- [x] Review the file.
- [x] Remove duplicated portions
- [x] Check for outdated links
