### ISSUE TITLE
Move Functions to the Top

### ISSUE THREAD

**Issue by Kacaii** [Kacaii/Senac-Coding#5]
This might help improve readability.
They dont have _side effects_, so it should be an easy fix.

## TODO List

- [x] Open desafioDeArray.js
- [x] Find the Functions.
- [x] Verify if its actually **safe** to move them.
- [x] Move the functions to the top of the file.
- [x] Commit.
